### ISSUE TITLE
Pagina's laden niet met HTTPS

### ISSUE THREAD

**Issue by mrombout** [Avans/Advanced-Algorithms#1]
Pagina's kunnen niet geladen worden bij het bezoeken van de website via HTTPS. Dat is vervelend bij het gebruik van bijvoorbeeld de browser extensie HTTPS Everywhere.

**Comment by PaulWagener** [comment]
Fixed in https://github.com/Avans/Algoritmiek-2/commit/99f1bbf22877d7bfccc425a465f11f2b1ecab1a2
